language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "node"
before_install:
  - npm install -g npm@latest
  - printf "//npme-private.npmjs.com/:_authToken=${NPM_TOKEN}\n@npminc:registry=https://npme-private.npmjs.com" >> ~/.npmrc
